-- CRIANDO BANCO DE DADOS

CREATE DATABASE EXEMPLO_AULA_7;



-- CRIANDO A TABELA NOMES 
CREATE TABLE NOMES(
	id INT,
	nome VARCHAR(10),
	UF CHAR(2),
	PRIMARY KEY (id)
);

-- CRIANDO UMA SEQUÊNCIA 
 CREATE SEQUENCE NOMES_SEQ
	START WITH 0 
	increment BY 1;

-- INSERINDO VALORES NA TABELA NOMES
INSERT INTO NOMES
VALUES	(NEXT VALUE FOR nomes_seq,'João','SP'),(NEXT VALUE FOR nomes_seq,'Pedro','SP'),(NEXT VALUE FOR nomes_seq,'Maria','SP'),
       	(NEXT VALUE FOR nomes_seq,'Paula','SP'),(NEXT VALUE FOR nomes_seq,'Paula','SP'),(NEXT VALUE FOR nomes_seq,'João','BA'),
	(NEXT VALUE FOR nomes_seq,'Pedro','BA'),(NEXT VALUE FOR nomes_seq,'Maria','BA'),(NEXT VALUE FOR nomes_seq,'Paula','BA'),
	(NEXT VALUE FOR nomes_seq,'João','SP'),(NEXT VALUE FOR nomes_seq,'João','SP'),(NEXT VALUE FOR nomes_seq,'Paula','SP');



-- CRIANDO A TABELA IDADE_A
CREATE TABLE IDADE_A(
	id INT,
	nome VARCHAR(10),
	idade INT,
	PRIMARY KEY (id)
);

INSERT INTO IDADE_A
VALUES 	(0,'João',18),(1,'Pedro',19),(2,'Maria',20),(3,'Paula',21);



-- CRIANDO A TABELA IDADE_B
CREATE TABLE IDADE_B(
	id INT,
	nome VARCHAR(10),
	idade INT,
	PRIMARY KEY (id)
);

INSERT INTO IDADE_B
VALUES 	(0,'João',18),(1,'Pedro',23),(2,'Maria',24),(3,'Paula',25);



-- UNIR AS INFORMAÇÕES DAS 2 TABELAS
SELECT
	NOME,
	IDADE
FROM
	IDADE_A

UNION
SELECT
	NOME,
	IDADE
FROM
	IDADE_B;



-- UNIR AS INFORMAÇÕES (DISTINTAS) DAS 2 TABELAS (SEM EXCLUIR A INTERSECÇÃO)
SELECT
	NOME,
	IDADE
FROM
	IDADE_A

UNION ALL
SELECT
	NOME,
	IDADE
FROM
	IDADE_B;



-- EXCEPT
SELECT
	NOME,
	IDADE
FROM
	IDADE_A
EXCEPT
SELECT
	NOME,
	IDADE
FROM
	IDADE_B;



-- INTERSECT
SELECT
	NOME,
	IDADE
FROM
	IDADE_A
INTERSECT
SELECT
	NOME,
	IDADE
FROM
	IDADE_B;



-- CRIANDO A TABELA CLIENTES
CREATE TABLE CLIENTES(
	cpf CHAR(11),
	nome VARCHAR(10),
	PRIMARY KEY (cpf)
);

-- INSERINDO OS DADOS
INSERT INTO CLIENTES
VALUES 	('18374177098','Arthur'),('17060231030','Bruno'),('23878596693','Filipe'),
	('44192841886','Guilherme'),('59862616156','Hariamy'),('88567582458','Hugo'),
	('95448038662','Igor'),('79845532209','Matheus'),('73145743244','Noah');



-- CRIANDO A TABELA DE SALDO
CREATE TABLE SALDO(
	cpf CHAR(11),
	saldo REAL,
	PRIMARY KEY (cpf)
);

INSERT INTO SALDO
VALUES 	('17060231030',100),('44192841886',200),('88567582458',300),('79845532209',400),('11654518590',500);



-- CRIAR A TABELA IDADE
CREATE TABLE IDADE(
	cpf CHAR(11),
	idade INT,
	PRIMARY KEY (cpf)
);

INSERT INTO IDADE
VALUES 	('17060231030',18),('23878596693',19),('59862616156',20),('95448038662',21),
       	('73145743244',22),('57437935228',23);



-- INNER - JUNTAR AS INFORMAÇÕES DA TABELA CLIENTES COM A TABELA SALDO
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
INNER JOIN
	SALDO AS B
ON
	A.cpf = B.cpf;



-- LEFT JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
LEFT JOIN
	SALDO AS B
ON
	A.cpf = B.cpf;



-- RIGHT JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
RIGHT JOIN
	SALDO AS B
ON
	A.cpf = B.cpf;



-- LEFT EXCLUDING JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
LEFT JOIN
	SALDO AS B
ON
	A.cpf = B.cpf
WHERE
	B.cpf IS NULL;



-- RIGHT EXCLUDING JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
RIGHT JOIN
	SALDO AS B
ON
	A.cpf = B.cpf
WHERE
	A.cpf IS NULL;



-- FULL OUTER JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
FULL OUTER JOIN
	SALDO AS B
ON
	A.cpf = B.cpf;



-- FULL EXCLUDING OUTER JOIN
SELECT
	A.cpf,
	A.nome,
	B.saldo
FROM
	CLIENTES AS A
FULL OUTER JOIN
	SALDO AS B
ON
	A.cpf = B.cpf
WHERE
	A.cpf IS NULL OR B.cpf IS NULL;



-- INNER - JUNTAR AS INFORMAÇÕES DA TABELA CLIENTES, SALDO E IDADE
SELECT
	A.cpf,
	A.nome,
	B.saldo,
	C.idade
FROM
	CLIENTES AS A
INNER JOIN
	SALDO AS B
ON
	A.cpf = B.cpf
INNER JOIN
	idade AS C
ON
	A.cpf = C.cpf;



-- CRIANDO UMA VIEW
CREATE VIEW INFO_CLIENTES AS
SELECT
	A.cpf,
	A.nome,
	B.saldo,
	C.idade
FROM
	CLIENTES AS A
INNER JOIN
	SALDO AS B
ON
	A.cpf = B.cpf
INNER JOIN
	IDADE AS C
ON
	A.cpf = C.cpf;

SELECT * FROM INFO_CLIENTES;